[package]
name = "body-proxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.22"
proxy-wasm = "0.2.0"
serde_json = "1.0.120"
wasm-bindgen = "0.2.79"
